### ISSUE TITLE
A-factor units in chemkin string?

### ISSUE THREAD

**Issue by cfgoldsmith** [cfgoldsmith/RMG-Py#18]
When we print the chemkin string, are the default units for length cm? m?

In our rate rules (and seedMech and training data), we give units for A in m^2/mol-s. The units in the chemkin string are 10^6 higher.
For example: CH2* + H* --> CH3* + X has:
```
SurfaceArrhenius(A=(3.09e+19,'m^2/(mol*s)'), n=-0.087, Ea=(57200,'J/mol')
```
but the chemkin string is:
```
HX(5)+CH2X(19)=vacantX(3)+CH3X(10) 3.090e+25 -0.087 13.671 
```
The difference in activation energy is a unit conversion, J/mol to kcal/mol. But why the factor of six difference in A-factor? If it were cm^2/mol-s, that would make sense, because that is the default length in chemkin (I think), but then it should be multiplied by 1E4, not 1E6.

**Comment by cfgoldsmith** [comment]
I'm guessing the 1E6 comes from m^3/mol-s --> cm^3/mol-s for gas phase, and we haven't fixed it.
Thoughts?

**Comment by rwest** [comment]
Yes

**Comment by rwest** [comment]
Well, I guess that had to be fixed eventually, so may as well have been tonight, but wasn't what I had originally planned for the evening. (I was hoping to get those graphs plotted!).

Think it's now working: I get
`HX(19)+CH2X(37)=site(18)+CH3X(22)                   3.090e+23 -0.087    13.671  `
for that reaction.
Also, I added `   STICK` for the sticking coefficients.
The chemkin file is still missing surface site density info etc, but is much closer to compatible.

**Comment by rwest** [comment]
So, to clarify, the chemkin file is now output in combinations of cm, molecules or moles, and time.
Unfortunately, the current implementation has a potential weakness: were someone crazily to specify a reaction library rate in units of minutes or hours instead of seconds, this would not get converted into seconds before printing in the chemkin file, causing a mistake.

Probably ought to fix that at some point, just in case.

**Comment by cfgoldsmith** [comment]
Great! Thank you. I'll close for now. We can come back to the time-units conversion later on...
