### ISSUE TITLE
Incrementing bonds to surface causes charge.

### ISSUE THREAD

**Issue by mazeau** [cfgoldsmith/RMG-Py#26]
This causes problems in the Surface_Dissiation family.

When you have a surface site "atom" with a single bond to an adsorbate, then increment that bond to a double bond, without doing anything else to it, RMG decides/infers/deduces the atom must now have a negative charge (calculated from valence counting rules, presumably).  It then says the structure is forbidden as we don't allow charged molecules. 

For gas phase atoms you would never do an INCREMENT_BOND action in isolation, there would always be a paired DECREMENT_BOND, BREAK_BOND, or DECREMENT_RADICAL or something.

Do we make a new action type to deal with this? or make the bond increment/decrement rules special for surface sites? or something else?

**Comment by rwest** [comment]
I *think* we solved this by modifying the code which calculates atomic charge (by counting bonds, valencies, lone pairs, radicals, etc.) so that surface sites (`X`) are always neutral, no matter how many of each of the above things they have.
Hopefully @mazeau will put the magic words "closes #26" in the commit message for that commit, and it will all work out beautifully :)
(Until we decide that it was a horrible idea)

**Comment by mazeau** [comment]
I have already made the commit but I'll close the issue here
